[package]
name = "rustic-diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.3"
plotters = "0.3.6"
rand = "0.8.5"
use = "0.0.1-pre.0"

[profile.dev]
opt-level = 1               # Use better optimizations.
